# Redirect rule to fix the broken contact page link
[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 301
  force = true

[build]
  command = "echo 'No build command specified'"
  publish = "."

[functions]
  directory = "netlify/functions" 