import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** Shared v2 theme — keep in sync with blog shell. */
export default {
  darkMode: 'class',
  content: [
    './blog/**/*.html',
    './index.html',
    './products/**/*.html',
    './pages/**/*.html',
    './buy-moringa-powder-australia/**/*.html',
    './shared/js/**/*.js',
    './scripts/templates/v2/**/*.html',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fdf9ee',
        'forest-deep': '#1A2E22',
        'on-primary': '#ffffff',
        'outline-variant': '#bec9c1',
        'primary-fixed': '#a1f3cd',
        'tertiary-container': '#4e6355',
        'surface-tint': '#106b4d',
        'on-surface': '#1c1c15',
        'secondary-container': '#fe8760',
        'on-error': '#ffffff',
        'on-primary-container': '#97e8c3',
        'surface-variant': '#e6e2d7',
        'on-tertiary-fixed': '#0b1f14',
        'primary-fixed-dim': '#86d7b2',
        primary: '#005139',
        'terracotta-clay': '#D66844',
        'on-background': '#1c1c15',
        'on-secondary-fixed': '#3a0b00',
        'tertiary-fixed': '#d0e8d6',
        'surface-container-highest': '#e6e2d7',
        'on-tertiary-fixed-variant': '#374b3e',
        'error-container': '#ffdad6',
        background: '#fdf9ee',
        'pure-white': '#FFFFFF',
        'inverse-on-surface': '#f4f0e6',
        'on-primary-fixed-variant': '#005139',
        'inverse-primary': '#86d7b2',
        'parchment-base': '#F5F1E6',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed-dim': '#b5ccbb',
        'on-secondary-container': '#732001',
        'surface-bright': '#fdf9ee',
        error: '#ba1a1a',
        outline: '#6f7a73',
        tertiary: '#364b3e',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#002115',
        'surface-container-high': '#ece8dd',
        'on-surface-variant': '#3f4943',
        'secondary-fixed-dim': '#ffb59e',
        'on-tertiary-container': '#c6decc',
        'moringa-leaf': '#0F6B4D',
        'inverse-surface': '#323129',
        'surface-container': '#f2eee3',
        'secondary-fixed': '#ffdbd0',
        'on-tertiary': '#ffffff',
        secondary: '#a0401f',
        'surface-dim': '#dddacf',
        'primary-container': '#0f6b4d',
        'surface-container-low': '#f7f3e8',
        'on-secondary': '#ffffff',
        'on-secondary-fixed-variant': '#802909',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        'margin-mobile': '20px',
        gutter: '24px',
        'section-gap': '80px',
        'margin-desktop': '64px',
        base: '8px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [forms, containerQueries],
};
