const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("Deploying ARKIVE contracts to Base Sepolia...");

  // Deploy PointsSystem first
  const PointsSystem = await hre.ethers.getContractFactory("PointsSystem");
  const pointsSystem = await PointsSystem.deploy();
  await pointsSystem.waitForDeployment();
  const pointsAddress = await pointsSystem.getAddress();
  console.log("PointsSystem deployed:", pointsAddress);

  // Deploy UserRegistry
  const UserRegistry = await hre.ethers.getContractFactory("UserRegistry");
  const userRegistry = await UserRegistry.deploy();
  await userRegistry.waitForDeployment();
  const userAddress = await userRegistry.getAddress();
  console.log("UserRegistry deployed:", userAddress);

  // Deploy PostRegistry with PointsSystem address
  const PostRegistry = await hre.ethers.getContractFactory("PostRegistry");
  const postRegistry = await PostRegistry.deploy(pointsAddress);
  await postRegistry.waitForDeployment();
  const postAddress = await postRegistry.getAddress();
  console.log("PostRegistry deployed:", postAddress);

  // Deploy VaultRegistry
  const VaultRegistry = await hre.ethers.getContractFactory("VaultRegistry");
  const vaultRegistry = await VaultRegistry.deploy();
  await vaultRegistry.waitForDeployment();
  const vaultAddress = await vaultRegistry.getAddress();
  console.log("VaultRegistry deployed:", vaultAddress);

  // Authorise PostRegistry to call PointsSystem
  await pointsSystem.authoriseCaller(postAddress);
  console.log("PostRegistry authorised to award points");

  // Save addresses to frontend
  const addresses = {
    PointsSystem: pointsAddress,
    UserRegistry: userAddress,
    PostRegistry: postAddress,
    VaultRegistry: vaultAddress,
    deployedAt: new Date().toISOString(),
    network: "baseSepolia",
    chainId: 84532
  };

  const outputPath = path.join(__dirname, "../../frontend/src/config/contracts.js");
  const content = `// Auto-generated by deploy script
export const CONTRACT_ADDRESSES = ${JSON.stringify(addresses, null, 2)};
`;
  fs.writeFileSync(outputPath, content);
  console.log("Contract addresses saved to frontend/src/config/contracts.js");

  // Copy ABIs to frontend
  const contractNames = ["PointsSystem", "UserRegistry", "PostRegistry", "VaultRegistry"];
  for (const name of contractNames) {
    const artifact = await hre.artifacts.readArtifact(name);
    const abiPath = path.join(__dirname, `../../frontend/src/contracts/${name}.json`);
    fs.writeFileSync(abiPath, JSON.stringify({ abi: artifact.abi }, null, 2));
    console.log(`${name} ABI copied to frontend`);
  }

  console.log("\nAll contracts deployed successfully.");
  console.log("Addresses:", addresses);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
